# Macro file for example B4
# 
# To be run preferably in batch, without graphics:
# % exampleB4[a,b,c,d] run2.mac
#
#/run/numberOfThreads 4
/run/initialize

# Default kinemtics: 
# /gun/particle e- 
# /gun/energy 5 GeV

# beam energy 
/b4/beamE    5 GeV
/b4/beamEsig 20 MeV

# beam raster 
/b4/rasterx 4.0 mm
/b4/rastery 4.0 mm

# beam direction 
/b4/beampointx 0.0 mm
/b4/beampointy 0.0 mm

/run/printProgress 10
/run/beamOn 1000
